name: build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker://pandoc/core
      with:
        entrypoint: bin/build

    - uses: amondnet/now-deployment@v2.0.2
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        now-org-id: ${{ secrets.ZEIT_ORG_ID }}
        now-project-id: ${{ secrets.ZEIT_PROJECT_ID }}
        now-args: "--prod"
